name: DVC Tracking with Github Actions
on: 
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  run:
    if: github.event.pull_request.merged==true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          make install 
          dvc pull
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md
          dvc metrics diff --show-md main > report.md
          gh pr comment ${{github.event.pull_request.number}} -F report.md
